name: New Submission
description: Start a new submission of glacier outlines to the GLIMS database
title: "[New Submission]: <Submitters Name>, glaciers outlines of <Region>, <List or Range of Years>"
labels:
  - "new submission"
projects: ["glims-nsidc/projects/1"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to start a new submission of one or more glacier outlines to the GLIMS Glacier Database.

        For a description of the submission process and the information and files required for a submission, please see [How to submit new glacier outlines to the GLIMS](https://glims-submissions-docs.readthedocs.io/en/latest/submitting_new_outlines.html)

        Please update the title field, with your name as the _submitter_, the name of the country or region containing your outlines and the year or years of the outlines.

        For example, "[New Submission]: Agassiz, glacier outlines of Switzerland, 1840”.


  - type: markdown
    attributes:
      value: '# Geographic Region
        
        These fields are required to define the geographic region for the glacier outlines you are submitting.'
        
  - type: input
    id: rc_id
    attributes:
      label: Regional Center ID
      description: The ID number of the Regional Center that covers the outlines you are submitting.  For a list of Regional Center IDs, see [GLIMS Regional Centers](https://www.glims.org/maps/nsidc_rc_table_public.html).
    
    validations:
      required: true
      
  - type: input
    id: region_label
    attributes:
      label: Geographic Region
      description: |
        The common name for the geographic region containing the glacier outlines.  For country inventories please use the country name.  For multi-national regions, please use the commonly accepted name for this region, for example North America, European Alps, Himalaya, High Mountain Asia.  For smaller regions, please give the state, mountain range or other commonly recognized term.
    validations:
        required: true

  - type: markdown
    attributes:
      value: '# Personnel

        The person submitting the outlines to GLIMS is the _Submitter_.  This is usually the person completing this form.  Other people who helped with the mapping are _Analysts_.'

  - type: input
    id: submittor_name
    attributes:
      label: Submitter Name
      description: |
        Please provide surname, given name, institution, address, email

        For example:
        `Agassiz, Louis, University of Neuchâtel, Avenue du 1er-Mars 26, CH - 2000, Neuchâtel, Neuchâtel, Canton of Neuchâtel, Switzerland`
    validations:
      required: true

  - type: textarea
    id: analysts
    attributes:
      label: Analysts
      description: |
        Please add the contact information of anyone else that contributed to mapping the glacier outlines.  Use a separate line for each new analyst.

        For example:
        `von Humbolt, Alexander, Department of Mines, Principality of Bayreuth, Bayreuth, Germany`
        `Lyell, Charles, Department of Geology Kings College London, Kings College London, Strand, London WC2R 2LS, United Kingdom`
    validations:
      required: false

  - type: markdown
    attributes:
      value: '# Files

        Please provide information about data and metadata files you are providing.'

  - type: input
    id: file_name
    attributes:
      label: Glacier outline file
      description: |
        Please provide the name of the file containing the vector features for the glacier outlines you are submitting.

        Accepted files formats are: ESRI Shapefiles and GeoJSON

        Please refer to [GLIMS File Format Requirements](https://glims-submissions-docs.readthedocs.io/en/latest/submitting_new_outlines.html#glacier-outlines-and-other-glacier-features) for information about the file content and vector feature attributes required.
    validations:
      required: true

  - type: input
    id: file_size
    attributes:
      label: Glacier outline file size in bytes
    validations:
      required: true
       
  - type: input
    id: sources_file_name
    attributes:
      label: Data sources file names
      description: |
        We require information about the data sources (images, dems or maps) used to create outlines.  These sources may be included in the Glacier Outline File or as a seprate file.

        Please refer to [GLIMS Submission Guide]() for information about the file content
    validations:
      required: false

  - type: textarea
    id: additional_files
    attributes:
      label: Additional files
      description: |
        Please provide a list of any additional files you are providing and a description of the contents of these files.

        For example:
        `data_dictionary.txt, a list of attributes in glaciers.shp`
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Describe Your Analysis Methods"

  - type: input
    id: analysis_time
    attributes:
      label: Date analysis was performed
      description: |
        Please provide the date on which the outlines were mapped in ISO8601 format (YYYY-MM-DD)

        This date is used for tracking in the database.  For large mapping efforts over longer periods of time, choose a representative date.  For example, if glaciers were mapped during the period August through November 2026, 2026-08-01, 2026-10-01, 2026-11-01 are all acceptable dates.
        
    validations:
      required: true
      
  - type: checkboxes
    id: source_type
    attributes:
      label: |
        What types of source data were used to map outlines?
      description:   |
        Please select all that apply.

        Name of data source, image id, and centroid or polygon defining the spatial extent of each source should be included as attributes for individual glacier outlines shapefile (or GeoJSON) or as a separate file.  See [New Submission Guidelines](https://glims-submissions-docs.readthedocs.io/en/latest/submitting_new_outlines.html) for guidelines. 
      options:
        - label: Satellite Imagery
        - label: Aerial Imagery
        - label: DEM
        - label: Published Map
        - label: Field Survey
    validations:
      required: true
      
  - type: checkboxes
    id: processing
    attributes:
      label: "Processing"
      description: Please check all processing steps applied to data sources before mapping outlines.
      options:
        - label: Image transformed from latitude, longitude to projected coordinates.
        - label: Image converted from image coordinates to geographic coordinates.
        - label: Image orthorectified?
        - label: Image DN converted to radiance.
        - label: Image radiance corrected for solar geometry.
        - label: Image radiometrically corrected.
        - label: Model radiometric correction applied.
        - label: Image corrected for anisotropic reflectance.
        - label: Terrain correction applied.
        - label: Band ratio or linear transform applied.
        - label: Spatial filtering applied.
        - label: Geomorphological analysis used.
        - label: Texture analysis used.
    validations:
      required: false

  - type: textarea
    id: process_description
    attributes:
      label: Please briefly describe your mapping method
      description: Provide a single sentence that describes the mapping method (manual, semi-automated, automated) and the sources used for mapping.
      placeholder: "Example: Semi-automated mapping from Landsat satellite images and SRTM digital elevation model"
    validations:
      required: true

  - type: dropdown
    id: manual_digitization
    attributes:
      label: Method of digitization
      description: Were outlines digitized by hand or automatically? If outlines were created automatically and then edited by hand, please indicate the estimated percentage of manual digitization in the following section.
      options:
        - Manual
        - Automatic
        - Automatic with manual editing
    validations:
      required: true

  - type: input
    id: percent_manual_editing
    attributes:
      label: What percentage of outlines were manually edited?
      value: "0"
    validations:
      required: false

  - type: dropdown
    id: classification_type
    attributes:
      label: Type of classification used
      description: Please indicate if a supervised or unsupervised classification method was used.  This can apply to traditional classification methods (e.g. ????) or deep-learning methods.
      options:
        - Supervised
        - Unsupervised
    validations:
      required: false

  - type: input
    id: supervised_title
    attributes:
      label: Type name of supervised classification method if used
      description: |
        Please use a common name for the supervised classification method
    validations:
      required: false

  - type: input
    id: usupervised_title
    attributes:
      label: Type name of unsupervised classification method if used
      description: |
        Please use a common name for the unsupervised classification method
    validations:
      required: false

  - type: input
    id: embargo_period
    attributes:
      label: Embargo period
      description: |
        If you wish the data to be embargoed, please provide the date for the end of the embargo period using ISO8601 (YYYY-MM-DD) or provide the number of months data are embargoed
      value: "0"
    validations:
      required: true

  - type: textarea
    id: analysis_tools
    attributes:
      label: Name of tool/platform used for mapping
      description: |
        Please enter the name of the tool or platform used for analysis, for example, ESRI ArcGIS.  Use a seperate line for each tool.
    validations:
      required: true

  - type: textarea
    id: citation
    attributes:
      label: Publication
      description: |
        Please provide the citation for any publications related to this submission, including a DOI and/or URL to the publication.
    validations:
      required: false
